% mota_combine(s,r)
%
% DESCRIPTION: Combines two partial structs generated by mota.m and
% outputs a single struct
function t = mota_combine(s,r)
  % checks
  if s.threshold1 ~= r.threshold1
    error('structs are not compatible : th1')
  end
  
  if s.threshold2 ~= r.threshold2
    error('structs are not compatible : th2')
  end
  
  if s.threshold3 ~= r.threshold3
    error('structs are not compatible : th3')
  end
  
  if s.MAXNOP ~= r.MAXNOP
    error('structs are not compatible : MAXNOP')
  end
  
  if s.numOfBootSamp ~= r.numOfBootSamp
    error('structs are not compatible : numOfBootSamp')
  end
  
  if s.sampleSize ~= r.sampleSize
    error('structs are not compatible : sampleSize')
  end
  
  different = find(r.X ~= s.X);
  if ~isempty(different)
    error('structs are not compatible : X')
  end
     
  
  par = [s.par, r.par];
  [par,ix] = sort(par);
  
  for i = 1 :length(par)-1
    if par(i+1)<=par(i)
      error('structs are not compatible : par')
    end
  end
  
  t = r;
  if ~strcmp(r.date,s.date)
    t.date = [r.date ' + ' s.date];
  end
  t.par = par;
  
  t.S = [s.S; r.S];
  t.S = t.S(ix,:);
  
  t.rSquared = zeros (2,length(t.X(1,:)),length(par));
  t.rSquared(:,:,1:length(s.par)) = s.rSquared;
  t.rSquared(:,:,length(s.par)+1:end) = r.rSquared;
  t.rSquared = t.rSquared(:,:,ix);
  

end